---
name: Deploy Source to GCP Cloud Funcstions

on:
  # Enabled to run actions with `workflow_dispatch`
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Set up google-cloud-sdk
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: hwakabh-gcp-developments
        service_account_email: github-ci-sa@hwakabh-gcp-developments.iam.gserviceaccount.com
        # Fetched SA key from GitHub secrets
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    # Fetch secrets from GitHub repository secrets and pass to command
    - name: Deploy Functions
      run: >
        gcloud functions deploy linebot-trash-notice
        --region="$GCP_REGION"
        --trigger-http
        --runtime=nodejs14
        --set-env-vars REDISHOST="$REDISHOST",REDISPORT="$REDISPORT",LINE_ACCESS_TOKEN="$LINE_ACCESS_TOKEN"
        --allow-unauthenticated
        --vpc-connector="projects/hwakabh-gcp-developments/locations/$GCP_REGION/connectors/$VPCC_NAME"
        --ignore-file="$GOOGLE_APPLICATION_CREDENTIALS"
      env:
        REDISHOST: ${{ secrets.REDISHOST }}
        REDISPORT: ${{ secrets.REDISPORT }}
        LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
        GCP_REGION: ${{ secrets.GCP_REGION }}
        VPCC_NAME: ${{ secrets.VPCC_NAME }}

    - name: Testing function call
      run: >
        gcloud functions call linebot-trash-notice
        --region="$GCP_REGION"
      env:
        GCP_REGION: ${{ secrets.GCP_REGION }}
