---
name: Print hello world
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v2  
    - name: My first step
      run: echo Hello my first action 